操作を記憶できるMemorableEditMapBlockAttacherの追加、InjectしRedo、Undoの仮実装
suupia/CarryBlock pull request #117
Opened 2023-10-31 16:06 UTC by tyPhoon-collab

Redo、Undoの仮実装をしました

ボタンはまだ諸問題があり、機能しませんが、KeyCode.Nを押すとUndo、KeyCode.Mを押すとRedoができるはずです

2023-11-01 04:38 UTC, suupia requested changes
MemorableEditMapBlockAttacherの修正例を貼っておきます。
```cs
    public class MemorableEditMapBlockAttacher
    {
        readonly Stack<OperationData> _stack;
        readonly Stack<OperationData> _redoStack;
        EditMapBlockAttacher _editMapBlockAttacher;
        
        public MemorableEditMapBlockAttacher(EditMapBlockAttacher editMapBlockAttacher, int capacity = 100)
        {
            _stack = new Stack<OperationData>(capacity);
            _redoStack = new Stack<OperationData>(capacity);
            _editMapBlockAttacher = editMapBlockAttacher;
        }
        
        public void AddPlaceable(EntityGridMap map , Vector2Int gridPos, IPlaceable addBlock)
        {
            var op = new OperationData(Operation.Add, gridPos, addBlock);
            Do(map, op);
            _redoStack.Clear();
            _stack.Push(op);
        }
        
        public void RemovePlaceable(EntityGridMap map, Vector2Int gridPos)
        {
            var op = new OperationData(Operation.Add, gridPos);
            Do(map, op);
            _redoStack.Clear();
            _stack.Push(op);
        }

        public bool Redo(EntityGridMap map)
        {
            var success =_redoStack.TryPop(out OperationData op);
            if (!success)
            {
                Debug.LogWarning("Cannot Redo.");
                return false;
            }

            Do(map, op);
            _stack.Push(op);
            return true;
        }

        public bool Undo(EntityGridMap map)
        {
            var success =_stack.TryPop(out OperationData op);
            if (!success)
            {
                Debug.LogWarning("Cannot Undo.");
                return false;
            }
            _redoStack.Push(op);
            
            Do(map, op.Reverse());
            return true;
        }

        public void Reset()
        {
            _stack.Clear();
            _redoStack.Clear();
        }

        void Do(EntityGridMap map, OperationData data)
        {
            switch (data.Operation)
            {
                case Operation.Add:
                    _editMapBlockAttacher.AddPlaceable(map, data.Coords, data.Placeable);
                    Debug.Log($"Add, {data.Coords}, {data.Placeable}");
                    break;
                case Operation.Remove:
                    _editMapBlockAttacher.RemovePlaceable(map,data.Coords);
                    Debug.Log($"Remove, {data.Coords}, {data.Placeable}");
                    break;
                default:
                    throw new ArgumentOutOfRangeException();
            }
        }

        public override string ToString()
        {
            return $"stack: {_stack}, redoStack: {_redoStack}";
        }
    }
    ```

2023-11-01 04:38 UTC, suupia commented on Assets/Projects/EditMapSystem/EditMap/Scripts/MemorableEditMapBlockAttacher.cs
> +        public new void RemovePlaceable(EntityGridMap map, Vector2Int gridPos)
現状、MemorableEditMapBlockAttacherはEditMapBlockAttacherを継承する必要がないと思います。
ポリフォーリズム等の機能を使っているところが見当たらないので、EditMapBlockAttacherを委譲する設計でよいと思います。
継承をやめること伴って、newキーワードを使用する必要がなくなります。

2023-11-01 04:38 UTC, suupia commented on Assets/Projects/ScopeSystem/Scripts/EditMapForPlayerScope.cs
> +            builder.Register(_ => new MemorableEditMapBlockAttacher(capacity:100),Lifetime.Scoped);
ここに関してはほかと同じように
```cs
            builder.Register<EditMapBlockAttacher>(Lifetime.Scoped);
            builder.Register<MemorableEditMapBlockAttacher>(Lifetime.Scoped).WithParameter("capacity", 100);
 ```
 と書くのがよいと思います。（委譲したバージョンの例です。）
おそらくコンストラクタのパラメータを設定したかったのだと思うのですが、リファレンスには以下のようにWithParameter()を使う例が上がっているので、そちらを使うのがよいかと思われます。
 [https://vcontainer.hadashikick.jp/ja/registering/register-type#register-type-specific-parameters](url)
正直stringで指定する形式なので、もっと良い方法はないのかとは思うのですが、自分自身勉強不足でわかっていないです。よい方法があったら、ぜひ教えてください。

 newをしてしまうと依存関係が増えた際にDIコンテナの便利なところを使えなくなってしまうので、避けたほうがよいと思います。
EditMapBlockAttacherをコンテナに登録することを嫌う場合にはFactoryを使うなど別の方法を使った方がよいのかなと思いますが、やったことないのでわからないです。
とりあえずはどちらも登録する方法でよいと思います。

2023-11-01 11:03 UTC, tyPhoon-collab commented on Assets/Projects/EditMapSystem/EditMap/Scripts/MemorableEditMapBlockAttacher.cs
> +        public new void RemovePlaceable(EntityGridMap map, Vector2Int gridPos)
レビューありがとうございます。その通りではあります。これに関しては横着したので修正しておきます。

せっかくなので議論しようと思います。
考えとしては、EditMapBlockAttacherとMemorableEditMapBlockAttacherを同じシグネチャで扱いたかったので、横着して継承を選択しました。
もし修正するならIEditMapBlockAttacherインタフェースを作って、EditMapBlockAttacherとMemorableEditMapBlockAttacherに実装させ、MemorableEditMapBlockAttacherにIEditMapBlockAttacherをDIしようと思っていますが、どうでしょうか

2023-11-01 11:08 UTC, tyPhoon-collab commented on Assets/Projects/ScopeSystem/Scripts/EditMapForPlayerScope.cs
> +            builder.Register(_ => new MemorableEditMapBlockAttacher(capacity:100),Lifetime.Scoped);
レビューありがとうございます。WithParameterのメソッドの情報ありがとうございます。従います

2023-11-01 13:59 UTC, suupia commented on Assets/Projects/EditMapSystem/EditMap/Scripts/MemorableEditMapBlockAttacher.cs
> +        public new void RemovePlaceable(EntityGridMap map, Vector2Int gridPos)
指摘していただきありがとうございます！
結論から申し上げますと、現時点では必要ないかなと考えたためインターフェースを追加する提案はしませんでした。
せっかく指摘いただいたので、作成する方向で良いと思います。よろしくお願いします。
参考までに以下に私の考えを述べておきます。

確かにIEditMapBlockAttacherインターフェースを追加するのは良いと思ったのですが、やはりポリフォーフィズムを使用していないと言う観点から今はまだ作成しなくても良いのかなと考え、提案はしなかったです。
もちろん作成しても害はないと思います。
```cs
public interface IEditMapBlockAttacher
{
    public void AddPlaceable(EntityGridMap map, Vector2Int gridPos, IPlaceable addBlock);
    public void RemovePlaceable(EntityGridMap map, Vector2Int gridPos);
}
```
 このようなインターフェースを追加することになると思うのですが、MemorableEditMapBlockAttacherがIEditMapBlockAttacherとして宣言された場合にpublicなメソッドである、Redo,Undo,Reset等は外部に見えなくなると思います。
それらのメソッドを呼ぶ場合にはキャスト等をする必要がありますが、現時点では該当するコードがないのでいらないかなと思いました。（パターンマッチで分岐する等のポリフォーフィズムを想定しています）
後々そのようなコードが出てくることがすでに確定しているのであれば、作成することに意義があると思います。

また、IEditMapBlockAttacherを作成することによりMemorableEditMapBlockAttacherのテスタビリティが上がることは間違いないので、モックオブジェクトの作成等を念頭においている場合は、作成したほうが良いと思います。

自分自身理解がまだ浅いため、見落としがあると思います。
インターフェースを現時点で作成することのメリットで考慮できていない部分がありましたらぜひ指摘お願いします！

2023-11-02 02:50 UTC, suupia approved these changes

2023-11-02 02:50 UTC, suupia commented on Assets/Projects/EditMapSystem/EditMap/Scripts/MemorableEditMapBlockAttacher.cs
> +        private IEditMapBlockAttacher _impl;
変数名についてですが、メンバ変数はできれば省略しないほうが良いかなと思います。細かいルールについては決めていないので、今度話し合いましょう。
あと、些細なことですが、このプロジェクトではprivateは省略する方向で書いています。あと、readonlyが付けられます。

2023-11-02 02:57 UTC, merged