オートセーブ機能を一度セーブするまでオートセーブが働かないように変更
suupia/CarryBlock pull request #24
Opened 2023-08-19 12:33 UTC by Sakai8121

2023-08-20 06:49 UTC, suupia requested changes
問題ないです。いい感じです！
細かいところで認識を擦り合わせておいた方が良いかなと思ったところをコメントしておきました。
実装ありがとうございます！

2023-08-20 06:49 UTC, suupia commented on Assets/Projects/EditMapSystem/EditMap/Scripts/AutoSaveManager.cs
> +    public bool CanAutoSave
些細なことですが、CanAutoSaveを上に書いてもらえると助かります。
「プロパティは変数と同じ括りで扱おう」と「publicを上に書こう」という考え方を持っているためです。

2023-08-20 06:49 UTC, suupia commented on Assets/Projects/EditMapSystem/EditMap/Scripts/AutoSaveManager.cs
> +    private bool _canAutoSave = false;
privateは省略すると良きです。これは「変数はできるだけprivateにすべきで、それならいちいち書かない方がよい」という考え方を持っているからです。
まあ、細かいので無視しても良いです。riderの設定を変えると良いかもです。

2023-08-21 10:57 UTC, Sakai8121 commented
すみません。今確認しました。メールは来てました。

2023年8月20日(日) 15:49 suupia ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> 問題ないです。いい感じです！
> 細かいところで認識を擦り合わせておいた方が良いかなと思ったところをコメントしておきました。
> 実装ありがとうございます！
> ------------------------------
>
> In Assets/Projects/EditMapSystem/EditMap/Scripts/AutoSaveManager.cs
> <https://github.com/suupia/SandboxShootoutTank/pull/24#discussion_r1299315154>
> :
>
> > @@ -0,0 +1,10 @@
> +public class AutoSaveManager
> +{
> +    private bool _canAutoSave = false;
> +
> +    public bool CanAutoSave
>
> 些細なことですが、CanAutoSaveを上に書いてもらえると助かります。
> 「プロパティは変数と同じ括りで扱おう」と「publicを上に書こう」という考え方を持っているためです。
> ------------------------------
>
> In Assets/Projects/EditMapSystem/EditMap/Scripts/AutoSaveManager.cs
> <https://github.com/suupia/SandboxShootoutTank/pull/24#discussion_r1299315335>
> :
>
> > @@ -0,0 +1,10 @@
> +public class AutoSaveManager
> +{
> +    private bool _canAutoSave = false;
>
>
> privateは省略すると良きです。これは「変数はできるだけprivateにすべきで、それならいちいち書かない方がよい」という考え方を持っているからです。
> まあ、細かいので無視しても良いです。riderの設定を変えると良いかもです。
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/suupia/SandboxShootoutTank/pull/24#pullrequestreview-1585811445>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A7C3PKNG5NOV4VMC5ETKMSLXWGXQVANCNFSM6AAAAAA3WRTGYE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-08-27 00:45 UTC, suupia commented
再度プルリクをしてもらえるとありがたいです。

2023-08-27 11:26 UTC, suupia approved these changes

2023-08-27 11:26 UTC, merged